---
- name: "Update ElasticSearch config"
  ansible.builtin.template:
    src: "elasticsearch.yml.j2"
    dest: "/etc/elasticsearch/elasticsearch.yml"
    owner: "root"
    group: "elasticsearch"
    mode: "0660"
  notify: "Restart elasticsearch"

- name: "Update Kibana config"
  ansible.builtin.template:
    src: "kibana.yml.j2"
    dest: "/etc/kibana/kibana.yml"
    owner: "root"
    group: "kibana"
    mode: "0660"
  notify: "Restart kibana"