---
- name: "Copy packages"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: "{{ elastic_deb_file }}"
      dest: "/tmp/{{ elastic_deb_file | basename}}"
    - src: "{{ kibana_deb_file }}"
      dest: "/tmp/{{ kibana_deb_file | basename}}"

- name: "Install ElasticSearch"
  ansible.builtin.apt:
    deb: "/tmp/{{ elastic_deb_file | basename}}"

- name: "Install Kibana"
  ansible.builtin.apt:
    deb: "/tmp/{{ kibana_deb_file | basename}}"