---
- name: "Add gpg key"
  ansible.builtin.apt_key:
    url: "https://packages.fluentbit.io/fluentbit.key"
    keyring: "/usr/share/keyrings/fluentbit-keyring.gpg"
    state: "present"

- name: "Add repository"
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/fluentbit-keyring.gpg] https://packages.fluentbit.io/ubuntu/{{ ansible_distribution_release }} {{ ansible_distribution_release }} main"
    state: present

- name: "Install Fluent-bit"
  ansible.builtin.apt:
    name: "fluent-bit"
    state: "present"
  notify: "Restart fluent-bit"
  